### ISSUE TITLE
Query regarding the acceptance of extended papers for journal submission

### ISSUE THREAD

**Issue by ramsey-coding** [llm4code/2024#1]
I am reaching out to express my excitement about this recent initiative.

I have a query regarding the submission for this paper. Specifically, I am interested in knowing if extended versions of papers, enriched with additional content beyond the initial submission, will be accepted for review and potential publication in journal. 

If there is an option to submit expanded versions of original papers for journal, that would be greatly helpful for authors.

**Comment by UniverseFly** [comment]
Hi @ramsey-coding, thank you for reaching out. Sorry I cannot give you a definite answer because we (web chairs) primarily focus on web related issues. I highly suggest you directly email the 4 professors from the [organizing committee](https://llm4code.github.io/organization/) with LLM4Code Workshop in the title.

**Comment by UniverseFly** [comment]
Closing this issue now. Feel free to open any website-related issues.
